services:
  frontend:
    build: frontend
    ports:
      - 4200:4200
      - 5000:5000
    volumes:
      - type: bind
        source: ./secrets
        target: /secrets
  backend:
    build: backend
    expose:
      - 5000
