services:
  frontend:
    build: frontend
    ports:
      - 4200:4200
      - 5000:5000
    secrets:
      - site.crt
      - site.key
  backend:
    build: backend
    environment:
      DB_CONN_FILE: /run/secrets/database_conn.txt
      SESSION_SECRET_FILE: /run/secrets/session_secret.txt
    expose:
      - 5000
    secrets:
      - database_conn.txt
      - session_secret.txt
  # RDS databases are expensive, just run this as part of Docker
  database:
    image: mariadb:11.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_DATABASE: itsc4155
      MARIADB_USER: service
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
    expose:
      - 3306
    secrets:
      - db_password
      - db_root_password
    #volumes:
    #   - itsc4155db:/var/lib/mysql:rw

#volumes:
#  itsc4155db:

secrets:
  # The cert is not technically a secret, but is managed as one for consistency
  site.crt:
    file: ./secrets/site.crt
  site.key:
    file: ./secrets/site.key
  database_conn.txt:
    file: ./secrets/connection_string_docker.txt
  session_secret.txt:
    file: ./secrets/session_secret.txt
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
