import enum
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from argon2 import PasswordHasher
from sqlalchemy.inspection import inspect
import string, random


# Initialize SQLAlchemy and Password hasher
db = SQLAlchemy()
password_hasher = PasswordHasher()

# Class Model to return queries as dict
class ModelMixin:
    def to_dict(self):
        """Automatically converts all columns of the model to a dictionary."""
        return {c.key: getattr(self, c.key) for c in inspect(self).mapper.column_attrs}


def gen_unique_login_id(length=8, max_attempts=3):
    """Generate a unique login_id for a new User using UPPERCASE letters and 0-9 digits."""
    attempts = 0
    characters = string.ascii_uppercase + string.digits
    while attempts < max_attempts:
        login_id = ''.join(random.choice(characters) for _ in range(length))
        if not User.query.filter_by(login_id=login_id).first():
            return login_id
        attempts += 1
    raise Exception("Failed to generate a unique login_id after maximum attempts.")


#######################################################################
#                                                                     #
#                          DATABASE TABLES                            #
#                                                                     #
#######################################################################

# The user table
class User(UserMixin, ModelMixin, db.Model):
    """
    An new User instance.
        :param id: The auto-generated table ID.
        :type id: int
        :param login_id: Unique identifier for the user's login, generated by `gen_unique_login_id()`.
        :type login_id: str
        :param username: The user's login username.
        :type username: str
        :param password: The user's login password.
        :type password: str
        :param canvas_id: Unique identifier for the user on Canvas.
        :type canvas_id: str
        :param canvas_name: The user's name on Canvas.
        :type canvas_name: str
        :param canvas_token_password: The encrypted Canvas token, encrypted using the user's unencrypted password.
        :type canvas_token_password: str
        :param todoist_token_password: The encrypted Todoist token, encrypted using the user's unencrypted password.
        :type todoist_token_password: str
    """
    # Table primary key
    id = db.Column(db.Integer, primary_key=True)

    # Info for login
    login_id = db.Column(db.String(100), unique=True, nullable=False)
    username = db.Column(db.String(100), unique=False, nullable=False)
    password = db.Column(db.String(100), unique=False, nullable=False)

    # Canvas info for user
    canvas_id = db.Column(db.String(150), unique=True, nullable=False)
    canvas_name = db.Column(db.String(150), unique=False, nullable=False)
    
    # Tokens encrypted with password
    canvas_token_password = db.Column(db.String(200), unique=False, nullable=False)
    todoist_token_password = db.Column(db.String(200), unique=False, nullable=False)

    # Tokens encrypted with session key
    canvas_token_session = None         # Placeholder for encrypted token with session key
    todoist_token_session = None        # Placeholder for encrypted token with session key

    # When the `login_manager.user_loader` is run for the login, this is the parameter it will use 
    def get_id(self):
        return str(self.login_id)


# A representation of the different types of tasks
class TaskType(enum.Enum):
    assignment = 1


# The task table
# A representation of a Canvas assignment and the connected Todoist task
# This primarily exists to link tasks in Canvas and Todoist
class Task(ModelMixin, db.Model):
    """
    A new Task instance.
        :param id: The auto-generated table ID.
        :type id: int
        :param owner: The ID of the User that owns the task.
        :type owner: int
        :param task_type: The type of the task.
        :type task_type: TaskType
        :param canvas_id: The ID of the task in Canvas.
        :type canvas_id: str
        :param todoist_id: The ID of the task in Todoist.
        :type todoist_id: str
    """
    # Table primary key
    id = db.Column(db.Integer, primary_key=True)

    # Foreign key to owner
    owner = db.Column(db.Integer, db.ForeignKey(User.id), unique=False, nullable=False)

    # Type of the task
    task_type = db.Column(db.Enum(TaskType), unique=False, nullable=False)

    # IDs for Canvas and Todoist
    canvas_id = db.Column(db.String(15), unique=False, nullable=False)
    todoist_id = db.Column(db.String(15), unique=False, nullable=True)
