name: Angular tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: mayurrawte/github-angular-actions@v1.1.0
      with:
        version: 18.2
    - name: Lint with ng
      run: |
        ng lint
    - name: Unit test with ng
      run: |
        ng test --browsers=ChromeHeadless --watch=false frontend
